### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by wslyvh** [energywebfoundation/challenge#15]
Hi EW team,

I was wondering when you're expecting to publish the results of the challenge? 
The process still mentions June 26, 2020.
I assumed it would be 1 week later, as the challenge itself got extended, but that would mean last Friday. 

Looking forward to it! Thanks

**Comment by WendellCathcart** [comment]
Hi @wslyvh, thanks for reaching out. We'll be alerting everyone soon with the results.

**Comment by ValentinJesse** [comment]
Hi, Wendell! Who won the challenge ?

**Comment by WendellCathcart** [comment]
Hi, thanks for checking in. We'll announce today or tomorrow in a Medium post
